### ISSUE TITLE
change port 

### ISSUE THREAD

**Issue by ecsuae** [hinata/nginx-forward-proxy#1]
hi ,firstly I like to appreciate your help for such easy way to configure the proxy, can you guide how can I change the default port 3128 to 8080 ,is there possibility to add authentication also ?

**Comment by hinata** [comment]
> can you guide how can I change the default port 3128 to 8080

Please change the mapping port on the Docker host.
e.g. `docker run -p 8080:3128 ...`

> is there possibility to add authentication also ?

I’m not planning to.
You are able to free to fork this project.
